name: firebase_dynamic_links_example
description: Demonstrates how to use the firebase_dynamic_links plugin.

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  firebase_core:
    path: ../../submodules/flutterfire/packages/firebase_core/firebase_core
  firebase_dynamic_links:
    path: ../../submodules/flutterfire/packages/firebase_dynamic_links/firebase_dynamic_links
  flutter:
    sdk: flutter
  url_launcher: ^6.1.0

dependency_overrides:
  _flutterfire_internals:
    path: ../../submodules/flutterfire/packages/_flutterfire_internals
  firebase_core:
    path: ../../submodules/flutterfire/packages/firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../submodules/flutterfire/packages/firebase_core/firebase_core_platform_interface
  firebase_dynamic_links:
    path: ../../submodules/flutterfire/packages/firebase_dynamic_links/firebase_dynamic_links
  firebase_dynamic_links_platform_interface:
    path: ../../submodules/flutterfire/packages/firebase_dynamic_links/firebase_dynamic_links_platform_interface

flutter:
  uses-material-design: true
